version: 2

jobs:
  build:
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-
      - run: npm ci
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Running E2E tests with JUnit reporter
          command: npm run test-junit
      - store_test_results:
          path: junit-results
      - run:
          name: Running E2E tests with multiple reporters
          command: npm run test-multiple
      - store_test_results:
          path: multiple-results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  deploy:
    docker: # Specify executor for running deploy job
      - image: cimg/base:stable
    steps:
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run: # Install the AWS CLI if it is not already included in the docker image
          name: Install awscli
          command: sudo pip install awscli
workflows:
  version: 2
  say-hello-workflow:
    jobs:
       - build
       - deploy:
          requires:
            - build
          filters:
            branches:
              only: deploy